-- Criando a tabela que irá receber a carga de dados.
CREATE TABLE IF NOT EXISTS base_teste (
    "CPF" VARCHAR(20),
    "PRIVATE" INT,
    "INCOMPLETO" INT,
    "DATA_ULTIMA_COMPRA" DATE,
    "TICKET_MEDIO" DECIMAL(7,2),
    "TICKET_ULTIMA_COMPRA"  DECIMAL(7,2),
    "LOJA_MAIS_FREQUENTE" VARCHAR(40),
    "LOJA_ULTIMA_COMPRA" VARCHAR(40),
    "CPF_VALIDO" BOOLEAN,
    "CNPJ_LMF_VALIDO" BOOLEAN,
    "CNPJ_LUC_VALIDO" BOOLEAN    
);
